services:
  - type: web
    name: motorhead
    env: docker
    buildCommand: "./build-script.sh" # You should replace this with your actual build command.
    envVars:
      - key: PORT
        value: "8080"
      - key: MOTORHEAD_MAX_WINDOW_SIZE
        value: "25"
      - key: MOTORHEAD_LONG_TERM_MEMORY
        value: "true"
      - key: MOTORHEAD_MODEL
        value: "gpt-3.5-turbo"
      - key: REDIS_URL
        value: "redis://redis:6379"
    port: 8080

databases:
  - type: redis
    name: redis
    port: 6379

