services:
  - type: web
    name: motorhead
    env: docker
    buildCommand: "./build-script.sh" # Replace with your actual build command
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: "8080"
      - key: MOTORHEAD_MAX_WINDOW_SIZE
        value: "25"
      - key: MOTORHEAD_LONG_TERM_MEMORY
        value: "true"
      - key: MOTORHEAD_MODEL
        value: "gpt-3.5-turbo"
      - key: REDIS_URL
        value: "redis://redis:6379"


